on:
  push:
    branches:
      - main

name: Main

jobs:
  build_horizon:
    name: 'Build Horizon'
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release of Horizon
        uses: rez0n/actions-github-release@main
        id: horizon_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "amezianechayer/horizon"
          type: "stable"

      - run: curl -OL ${{ steps.horizon_release.outputs.browser_download_url }}
      - run: tar -zxvf horizon-${{ steps.horizon_release.outputs.release }}.tar.gz
      - run: rm -rf horizon-${{ steps.horizon_release.outputs.release }}.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: horizon-dist
          path: ./**

  build:
    name: 'Build'
    needs: build_horizon
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            file: windows
          - os: ubuntu-latest
            file: default

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: get deps
        run: go get
        env:
          CGO_ENABLED: 1
          GOPRIVATE: github.com/amezianechayer/*
          GONOSUMCHECK: github.com/amezianechayer/*

      - name: Fetch Horizon dist
        uses: actions/download-artifact@v4
        with:
          name: horizon-dist
          path: cmd/horizon/

      - name: OSXCross for CGO Support
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir ../../osxcross
          git clone https://github.com/plentico/osxcross-target.git ../../osxcross/target

      - name: Downgrade libssl
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list
          sudo apt update && apt-cache policy libssl1.0-dev
          sudo apt-get install libssl1.0-dev

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --parallelism 4 --rm-dist --skip-validate --snapshot --config .github/.goreleaser.${{matrix.file}}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPRIVATE: github.com/amezianechayer/*