name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Sync OpenAPI to ReadMe
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./spec/http.yml --key=${{ secrets.README_API_KEY }} --create